export const Jobs = [
      {
          id: 1,
          company: 'Shopee',
          job: 'Backend Software Engineer',
          rating: '3.6',
          type: 'Backend',
          time: '18 minutes ago',
          loc: 'Singapore',
          salary: 'S$6000 - S$7000 / mth',
          stack: ['C++', 'Python', 'Java'],
          logo: '/images/shopee.jpg'
      },
      {
          id: 2,
          company: 'TikTok',
          job: 'FullStack Software Engineer',
          rating: '4.6',
          type: 'FullStack',
          time: '20 days ago',
          loc: 'Japan',
          salary: 'S$6500 - S$10000 / mth',
          stack: ['C++', 'C', 'JavaScript', 'Ruby', 'MATLAB', 'Python', 'Java', 'React'],
          logo: '/images/tiktok.png'
      },
      {
          id: 3,
          company: 'Accenture',
          job: 'Frontend Software Engineer',
          rating: '4.5',
          type: 'Frontend',
          time: '3 days ago',
          loc: 'Thailand',
          salary: 'S$5000 - S$7500 / mth',
          stack: ['C', 'JavaScript', 'Figma', 'React'],
          logo: '/images/accenture.png'
      },
      {
          id: 4,
          company: 'TikTok',
          job: 'FullStack Software Engineer',
          rating: '4',
          type: 'FullStack',
          time: '20 minutes ago',
          loc: 'Singapore',
          salary: 'S$7500 - S$10000 / mth',
          stack: ['C++', 'C', 'JavaScript', 'Ruby', 'MATLAB', 'Python', 'Java', 'React'],
          logo: '/images/tiktok.png'
      },
      {
          id: 5,
          company: 'ByteDance',
          job: 'FullStack Software Engineer',
          rating: '1.3',
          type: 'FullStack',
          time: '55 minutes ago',
          loc: 'Japan',
          salary: 'S$6500 - S$9000 / mth',
          stack: ['C++', 'C', 'JavaScript', 'Ruby', 'MATLAB', 'Python', 'Java', 'React'],
          logo: '/images/bytedance.png'
      },
      {
          id: 6,
          company: 'TikTok',
          job: 'FullStack Software Engineer',
          rating: '4.6',
          type: 'FullStack',
          time: '40 minutes ago',
          loc: 'Japan',
          salary: 'S$7500 - S$10000 / mth',
          stack: ['C++', 'C', 'JavaScript', 'Ruby', 'MATLAB', 'Python', 'Java', 'React'],
          logo: '/images/tiktok.png'
      },
      {
          id: 7,
          company: 'GovTech',
          job: 'Backend Software Engineer',
          rating: '3',
          type: 'Backend',
          time: '12 minutes ago',
          loc: 'Singapore',
          salary: 'S$6500 - S$7500 / mth',
          stack: ['C++', 'Python', 'Java'],
          logo: '/images/govtech.png'
      },
      {
          id: 8,
          company: 'Shopee',
          job: 'Frontend Software Engineer',
          rating: '5',
          type: 'Frontend',
          time: '29 days ago',
          loc: 'Singapore',
          salary: 'S$3000 - S$9000 / mth',
          stack: ['C++', 'Python', 'Java'],
          logo: '/images/shopee.jpg'
      },
      {
          id: 9,
          company: 'Manulife',
          job: 'Frontend Software Engineer',
          rating: '4.5',
          type: 'Frontend',
          time: '10 hours ago',
          loc: 'Thailand',
          salary: 'S$4000 - S$5000 / mth',
          stack: ['C', 'JavaScript', 'Java', 'MATLAB'],
          logo: '/images/manulife.png'
      },
      {
          id: 10,
          company: 'Shopee',
          job: 'Backend Software Engineer',
          rating: '3.6',
          type: 'Backend',
          time: '22 minutes ago',
          loc: 'Singapore',
          salary: 'S$6000 - S$7000 / mth',
          stack: ['C++', 'Python', 'Java'],
          logo: '/images/shopee.jpg'
      },
      {
          id: 11,
          company: 'Singtel',
          job: 'FullStack Software Engineer',
          rating: '1.5',
          type: 'FullStack',
          time: '20 minutes ago',
          loc: 'Singapore',
          salary: 'S$6000 - S$7000 / mth',
          stack: ['C++', 'C', 'JavaScript', 'Ruby', 'MATLAB', 'Python', 'Java', 'React'],
          logo: '/images/singtel.png'
      },
      {
          id: 12,
          company: 'GovTech',
          job: 'Backend Software Engineer',
          rating: '3',
          type: 'Backend',
          time: '12 minutes ago',
          loc: 'Singapore',
          salary: 'S$6500 - S$7500 / mth',
          stack: ['C++', 'Python', 'Java'],
          logo: '/images/govtech.png'
      }
    ];
